import {StyleSheet} from 'react-native';
import fontFamily from '../../assets/fonts/fontFamily';

const styles = StyleSheet.create({
  createClassContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    marginBottom: 40,
  },
  selectCover: {
    paddingTop: 26,
    fontSize: 15,
    lineHeight: 19,
    fontFamily: fontFamily.book,
    color: '#334E68',
  },
  coverContainer: {
    marginTop: 12,
    width: '100%',
    backgroundColor: '#FAFAFC',
    borderColor: 'rgba(161, 174, 183, 0.1)',
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  registerButton: {
    marginTop: 21,
    height: 43,
    backgroundColor: '#F86A6A',
    marginHorizontal: 16,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  registerNowText: {
    lineHeight: 19,
    fontSize: 15,
    fontWeight: '500',
    color: '#fff',
    fontFamily: fontFamily.book,
  },
  mainContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
    justifyContent: 'space-between',
    paddingVertical: 32,
  },
  congoContainer: {
    paddingTop: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  crossButton: {position: 'absolute', left: 20, top: 64},
  congoText: {
    paddingTop: 86,
    fontSize: 23,
    fontWeight: 'bold',
    lineHeight: 29,
    color: '#102A43',
    letterSpacing: -0.3,
    fontFamily: fontFamily.book,
  },
  simpleText: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontSize: 15,
    lineHeight: 15,
    letterSpacing: -0.3,
    color: '#334E68',
    fontFamily: fontFamily.book,
  },
  shareFriendText: {
    fontSize: 15,
    letterSpacing: -0.3,
    lineHeight: 15,
    color: '#334E68',
    fontWeight: 'bold',
    fontFamily: fontFamily.book,
  },
  optionalView: {
    height: 76,
    backgroundColor: '#FAFAFC',
    borderColor: '#a1aeb7',
    borderRadius: 10,
    marginTop: 16,
  },
  postButton: {
    marginTop: 12,
    height: 43,
    width: 93,
    backgroundColor: '#F86A6A',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  postText: {
    fontSize: 15,
    fontWeight: '500',
    lineHeight: 19,
    letterSpacing: -0.3,
    color: '#fff',
    fontFamily: fontFamily.book,
  },
  inviteButton: {
    flexDirection: 'row',
    marginVertical: 16,
    marginHorizontal: 32,
    height: 48,
    backgroundColor: '#F86A6A',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inviteText: {
    fontWeight: '500',
    fontSize: 15,
    lineHeight: 15,
    letterSpacing: -0.3,
    color: '#fff',
    fontFamily: fontFamily.book,
  },
  liveButtonsContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingBottom: 120,
    paddingHorizontal: 10,
  },
  liveNow: {
    width: 128,
    height: 43,
    backgroundColor: '#fff',
    borderTopLeftRadius: 23,
    borderTopRightRadius: 23,
    borderBottomLeftRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  liveLatter: {
    width: 128,
    height: 43,
    backgroundColor: '#fff',
    borderTopLeftRadius: 23,
    borderTopRightRadius: 23,
    borderBottomRightRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  liveText: {
    fontFamily: fontFamily.book,
    lineHeight: 19,
    fontSize: 15,
    textAlign: 'center',
  },
  createClass: {
    alignSelf: 'center',
    paddingTop: 63,
    fontWeight: 'bold',
    fontSize: 15,
    lineHeight: 19,
    letterSpacing: -0.3,
    textAlign: 'center',
    fontFamily: fontFamily.book,
    color: '#334E68',
  },
  heading: {
    paddingTop: 24,
    fontSize: 15,
    lineHeight: 19,
    fontFamily: fontFamily.book,
    color: '#334E68',
  },
  typeButton: {
    backgroundColor: '#F5F5F5',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: 154,
    height: 35,
    margin: 8,
    borderRadius: 18,
  },
});

export default styles;
