const classData = [
  {
    classId: 123,
    className: 'HIIT',
    classType: 'HIIT',
    s3url: 'https://homepages.cae.wisc.edu/~ece533/images/sails.png',
    users3url: 'https://homepages.cae.wisc.edu/~ece533/images/sails.png',
    difficulty: 'medium',
    expectedDuration: 15,
    instructorUserId: 'derek',
    description: 'workout class',
    requiredEquipment: null,
    isPrivate: false,
    registeredUsers: 15,
    scheduledTime: new Date(),
    comments: null,
  },
  {
    classId: 123,
    className: 'HIIT',
    classType: 'HIIT',
    s3url: 'https://homepages.cae.wisc.edu/~ece533/images/sails.png',
    users3url: 'https://homepages.cae.wisc.edu/~ece533/images/sails.png',
    difficulty: 'medium',
    expectedDuration: 15,
    instructorUserId: 'derek',
    description: 'workout class',
    requiredEquipment: null,
    isPrivate: false,
    registeredUsers: 15,
    scheduledTime: new Date(),
    comments: null,
  },
];

export default classData;
