import {StyleSheet} from 'react-native';
import fontFamily from '../../assets/fonts/fontFamily';

const styles = StyleSheet.create({
  onImageContainer: {
    flexDirection: 'row',
    paddingHorizontal: 19,
    justifyContent: 'space-between',
    marginTop: 66,
    alignItems: 'center',
  },
  classTitleText: {
    fontWeight: 'bold',
    fontSize: 23,
    lineHeight: 29,
    letterSpacing: -0.3,
    color: '#102A43',
    fontFamily: fontFamily.book,
  },
  instructorName: {
    fontWeight: 'normal',
    fontSize: 15,
    lineHeight: 15,
    letterSpacing: -0.3,
    color: '#334E68',
    fontFamily: fontFamily.book,
  },
  dateAndTime: {
    paddingLeft: 11,
    fontSize: 15,
    lineHeight: 15,
    letterSpacing: -0.3,
    color: '#334E68',
    fontFamily: fontFamily.book,
  },
  liveIndicator: {
    marginLeft: 16,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#FF0E83',
  },
  liveNowText: {
    paddingLeft: 2,
    fontSize: 13,
    fontWeight: '900',
    lineHeight: 16,
    color: '#FF0E83',
    fontFamily: fontFamily.book,
  },
  registeredUserView: {
    flexDirection: 'row',
    paddingTop: 19,
    paddingLeft: 16,
    alignItems: 'center',
  },
  registeredUserCountView: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 32,
    height: 32,
    backgroundColor: '#F86A6A',
    borderRadius: 16,
    position: 'absolute',
    top: 19,
    left: 80,
  },
  registeredCount: {
    fontWeight: '900',
    fontSize: 10,
    lineHeight: 13,
    color: '#fff',
    fontFamily: fontFamily.book,
  },
  boldNumber: {
    paddingLeft: 80,
    fontSize: 15,
    fontWeight: 'bold',
    color: '#334E68',
    fontFamily: fontFamily.book,
  },
  registerButton: {
    marginTop: 21,
    height: 43,
    backgroundColor: '#F86A6A',
    marginHorizontal: 16,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  copyLinkButton: {
    marginTop: 21,
    height: 43,
    backgroundColor: '#FAFAFC',
    marginHorizontal: 16,
    borderRadius: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  registerNowText: {
    lineHeight: 19,
    fontSize: 15,
    fontWeight: '500',
    color: '#fff',
    fontFamily: fontFamily.book,
  },
  copyLinkText: {
    lineHeight: 19,
    fontSize: 15,
    fontWeight: '500',
    color: '#334E68',
    textAlign: 'center',
    fontFamily: fontFamily.book,
  },
  viewDivider: {height: 15, backgroundColor: '#f9f9f9', marginTop: 20},
  boldText: {
    fontSize: 15,
    lineHeight: 15,
    fontWeight: 'bold',
    letterSpacing: -0.3,
    color: '#334E68',
    fontFamily: fontFamily.book,
  },
  instructorView: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    alignItems: 'center',
    paddingTop: 20,
  },
  numOfClassessAndFollowers: {
    fontSize: 13,
    lineHeight: 16,
    fontWeight: 'bold',
    color: '#334E68',
    fontFamily: fontFamily.book,
  },
  normalText: {
    fontSize: 13,
    lineHeight: 16,
    color: '#334E68',
    fontFamily: fontFamily.book,
  },
  followingButton: {
    flexDirection: 'row',
    height: 32,
    width: 103,
    backgroundColor: '#F0F1F3',
    position: 'absolute',
    right: 0,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  followingText: {
    paddingLeft: 6,
    fontSize: 15,
    lineHeight: 15,
    letterSpacing: -0.3,
    color: '#334E68',
    fontFamily: fontFamily.book,
  },
  commentsContainer: {
    flex: 1,
    backgroundColor: '#fff',
    paddingHorizontal: 16,
    paddingTop: 13,
    paddingBottom: 40,
  },
  writeCommentView: {
    height: 40,
    backgroundColor: '#FAFAFC',
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#a1aeb7',
    width: '85%',
    marginLeft: 10,
    justifyContent: 'center',
    paddingLeft: 12,
  },
  commentTile: {
    backgroundColor: '#F0F1F3',
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#a1aeb7',
    width: '85%',
    marginLeft: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  userName: {
    fontSize: 15,
    lineHeight: 19,
    fontWeight: 'normal',
    color: '#102A43',
    fontFamily: fontFamily.book,
  },
  commentText: {
    fontSize: 13,
    lineHeight: 15,
    fontWeight: 'normal',
    color: '#334E68',
    paddingTop: 7,
    fontFamily: fontFamily.book,
  },
  avatar: {
    backgroundColor: '#191919',
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  tag: {
    position: 'absolute',
    width: 75,
    height: 24,
    backgroundColor: '#35BCDF',
    borderRadius: 30,
    bottom: 16,
    left: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  beginnerText: {
    fontSize: 13,
    lineHeight: 16,
    color: '#fff',
    fontFamily: fontFamily.book,
  },
  commentDateAndTime: {
    paddingLeft: 10,
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 1,
    color: '#334e68',
    textTransform: 'uppercase',
    fontFamily: fontFamily.book,
  },
});

export default styles;
